# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from train_on_gcp.predict_using_GCP_trained_model import container_predict, extract_response_top_prediction

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(-120, 0, 801, 131))
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("/home/idan/Desktop/ask-lily-logo.jpg"))
        self.label1.setObjectName("label1")

        self.toolButton1 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton1.setGeometry(QtCore.QRect(290, 150, 251, 41))
        self.toolButton1.setObjectName("toolButton1")

        self.textBrowser1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser1.setGeometry(QtCore.QRect(290, 190, 251, 81))
        self.textBrowser1.setObjectName("textBrowser1")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 140, 251, 271))
        self.label2.setText("")
        self.label2.setObjectName("label2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton1.setText(_translate("MainWindow", "Load and Classify Image"))
        self.toolButton1.clicked.connect(self.load_display_and_classify)


    def load_and_display_image(self):
        image_path, _ = QFileDialog.getOpenFileName()
        pixmap = QtGui.QPixmap(image_path)

        # adjust image to size of view
        hight = self.label2.geometry().height()
        width = self.label2.geometry().width()
        pixmap_adjusted = pixmap.scaled(hight, width)

        self.label2.setPixmap(pixmap_adjusted)
        return image_path

    def load_display_and_classify(self):
        image_file_path = self.load_and_display_image()
        file_name = os.path.basename(image_file_path)
        image_name = file_name.split(".")[0]

        port = 8080
        network_response = container_predict(image_file_path, image_name, port)
        top_prediction, probability = extract_response_top_prediction(network_response)
        self.textBrowser1.setText('Image was predicted as {} with {}% confidence.'.format(top_prediction,probability))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
